#! env/bin/python3

from requests import get
from bs4 import BeautifulSoup

import livre
import categorie
import fichiers


page = get("http://books.toscrape.com/")
if page.status_code == 200:

    # Suppression du dossier de sortie
    fichiers.supprimerDossiers()


    try:
        # -- Recherche des catégories et lancement des lectures
        soup = BeautifulSoup(page.content, "html.parser")
        liste = soup.find("ul", class_="nav nav-list").find("ul").find_all("a")
        liste.sort(key=lambda elem : elem.string)       # Affichage plus agréable
        print("Traitement en cours")

         # -- Création d'une barre de progression envoyée au module article pour l'affichage
        progression = str()
        for i, c in enumerate(liste):
            for j in range(14):
                if j <= int(i * 14 / len(liste)):
                    progression +="X"
                else:
                    progression +="–"

            # --
            categorie.lecture("http://books.toscrape.com/" + c["href"], progression)



    except AttributeError:
        print("\nErreur lors de la recherche d'une balise - Extraction impossible")     # Site modifié, revoir les soup.find


